const config = {
  webSecrect: process.env.WEB_SECRECT || "sO4NikHYPufZeQUZtwxfWJrqQg5pyQDM",
  webTokenExpires: parseInt(process.env.WEB_TOKEN_EXPIRES) || 30000,
  saltRounds: 10,
  apiSecrect: process.env.API_SECRECT || "Xn7GjOXy2NYaMGTQoAFTS75wXuXBmA6J",
  db_host: process.env.DB_HOST,
  db_user: process.env.DB_USER,
  db_password: process.env.DB_PASS,
  db_port: process.env.DB_PORT || "3306",
  db_database: process.env.DB_DATBASE,
  otp_expire_time: 300,
  otp_resend_time: 120,
  business_wallet_id: process.env.BUSINESS_WALLET_ID || "1",
  cash_deposit_charges: parseInt(process.env.CASH_DEPOSIT_CHARGES) || 2,
  email_host: process.env.EMAIL_HOST || "smtp.sendgrid.net",
  email_user: process.env.EMAIL_USER || "",
  email_pass: process.env.EMAIL_PASS || "",
  email_port: 587,
  max_order_reprocess: 4,
  userRole: {
    admin: 1,
    staff: 2,
    touradmin: 3,
    b2bpatner: 4,
    b2cpartner: 5,
    unverified: 8,
  },
  tables: {
    user: "rck_member",
    otp: "rck_otp",
    permission: "rck_member_permission",
    wallet: "rck_wallet_log",
    provider: "rck_provider",
    operator: "rck_operator",
    service: "rck_service",
    commission_template: "rck_commission_template",
    commission: "rck_commission_template_operator",
    providerCommission: "rck_commission_provider_operator",
    order: "rck_order",
    log: "rck_log",
    issue: "rck_issue",
  },
  debugLog: true,
  rkitConfig: {
    userid: "12345678",
    token: "123456789",
  },
  justrechargeConfig: {
    mobileNo: "",
    SUID: "",
    SUPD: "",
  },
  tuktukConfig: {
    mobileNo: "",
    APIKey: "",
  },
  non_OP_ID_inludes: [
    "",
    "N/A",
    "NA",
    "MANUAL SUCCESS",
    "AUTO",
    "SUCCESS",
    "SUCESS",
    "SUCCES",
    "REQ TO GET",
    "MSG",
    "UL",
    "-",
    "Fail",
    "Mobile",
    "Transaction Number",
    "&",
    "recharge pending",
    "N/A",
    "Success",
    "DP",
    "req to get",
    "N/A&  N.A",
    "response",
    "status",
    "PENDING",
    "Null",
  ],
  amount_charged: {
    allplan: 0.5,
    mobile: 0.2,
    singleplan: 0.4,
  },
};

module.exports = config;
